name: "Check code"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

python-pep8:
  name: Python formatting PEP8
  runs-on: ubuntu-20.04
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    with:
      python-version: 3.7
    - name: Install dependencies
      run: |
        pip install flake8
    - name: Run checking
      run: |
         flake8 .
